### ISSUE TITLE
Error: Could not find or load main class 

### ISSUE THREAD

**Issue by prodchia** [ForkFarmer/ForkFarmer#1]
I downloaded the jar, and tried to launch it on my windows computer. I complains "Error: Could not find or load main class ForkFarmer_0.6a.jar"

**Comment by ForkFarmer** [comment]
That is... strange. What Java runtime are you using? Make sure it's up to date.

**Comment by prodchia** [comment]
C:\Users\user>java -version
java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.301-b09, mixed mode)

**Comment by prodchia** [comment]
I figured it out. my JRE was corrupted.
