### ISSUE TITLE
I have writen 3 new functions

### ISSUE THREAD

**Issue by liyifeng** [ForkFarmer/ForkFarmer#15]
I have writen 3 new functions,I don't know is it necessary pull request to official main branch? or The FF official has their own plan。

the 3 feature is :
1. copy private key from chia to a fork . in context menu [Action]-[Copy private key from Chia]
2. copy plot dirs of chia to a fork . in context menu  [Action]-[Copy plot dirs from Chia]
3. show plot dir of a fork . in context menu  [Explore] - [show plot dirs]

**Comment by ForkFarmer** [comment]
It sounds like good features. I will merge what you create into main. 

I would suggest another context sub-menu for your features, they are "setup" options. Possibly below right below community

[setup]->[copy private key from Chia]
[setup]->[copy plot Dirs from Chia]
[setup]->[set pass file] <- move into under setup.

Also, thanks for your language localization effort! Can you make i18n load the English string, if the key is not available for the currently selected locale? That way if I add new features it will use english until someone fixes the properties file.

Thanks!

**Comment by liyifeng** [comment]
I am very happy to get your approval, and I will submit the 3 new features code later.
you are right,  the language localization function is not perfect, I will improve it later.

**Comment by ForkFarmer** [comment]
util.I18n.get(I18n.java:53), ResourceBundle.getString throws exception (doesn't return null).

 I added new PeerView column to test.
Caused by: java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key **PeerView.tableHeader.nodeIDColName**
	at java.base/java.util.ResourceBundle.getObject(ResourceBundle.java:564)
	at java.base/java.util.ResourceBundle.getString(ResourceBundle.java:521)
	at util.I18n.get(I18n.java:53)

**Comment by ForkFarmer** [comment]
Works perfect! Thanks!!!! 😄

**Comment by liyifeng** [comment]
> Works perfect! Thanks!!!! 😄

😁
