### ISSUE TITLE
Rename Staicoin to Stai

### ISSUE THREAD

**Issue by patiati** [ForkFarmer/ForkFarmer#19]
Please add support for Stai. It was recently renamed from Staicoin, they changed the name in the folders too.

**Comment by liyifeng** [comment]
I think the [Add Fork] in context menu can help you reposition the Stai。

**Comment by patiati** [comment]
thanks

**Comment by ForkFarmer** [comment]
Path is fixed in latest code pushed to GIT. Latest jar release in discord... eventually pushed here.
