### ISSUE TITLE
FF v2.7 draws almost none of its GUI elements

### ISSUE THREAD

**Issue by Qriist** [ForkFarmer/ForkFarmer#23]
Hey there, I'm trying to update 2.6 -> 2.7 and it's, well, not working. This screenshot depicting both versions is a couple minutes after a reboot on a system with no other known gfx issues. Not every fork has loaded dude to the staggered start, but you can see that the GUI is at least working correctly in 2.6

How do I fix this issue? Thanks!
![image](https://user-images.githubusercontent.com/26832022/163735503-39e0e5ca-8c40-41fc-a5fc-bb1587c5e26a.png)

**Comment by liyifeng** [comment]
try to delete FF_Settings.yaml

**Comment by robertocmsantos** [comment]
yes it worked. Thank you!

**Comment by Qriist** [comment]
> try to delete FF_Settings.yaml

thanks.... where do I find that? I just have FF sitting on my desktop and there's no yaml file.

**Comment by Qriist** [comment]
> try to delete FF_Settings.yaml

thanks, that fixed it!
