### ISSUE TITLE
The Chia balance is not displayed.

### ISSUE THREAD

**Issue by pantyushkin** [ForkFarmer/ForkFarmer#24]
After updating Chia to version 1.3.4, the balance is not displayed.
![Снимок экрана 2022-04-22 145646](https://user-images.githubusercontent.com/32091802/164709835-6b7f108c-efbd-4520-b73d-235fd72db151.png)

**Comment by ForkFarmer** [comment]
There is newer version in discord that fixes this issue. It will be pushed to github eventually.

**Comment by pantyushkin** [comment]
I can't log in to discord. When is the release planned?

**Comment by pantyushkin** [comment]
Ok. Thanks.
