### ISSUE TITLE
[proposed bug] Doesn't work Show peers at Ubuntu 

### ISSUE THREAD

**Issue by sykmer** [ForkFarmer/ForkFarmer#26]
Hi 
I have problem with Show peers at ubuntu 22.04 LTS.
When i run Show peers i got :
"chia show -a has been renamed to chia peer -a"

And i think that this it too bad because i think correctly is chia peer -c

Please fix it. 
Thank you
![image](https://user-images.githubusercontent.com/51207950/203526513-30024330-29e1-4804-8829-c5f8dfe91faa.png)

**Comment by ForkFarmer** [comment]
Yep. I'll fix it next release.

**Comment by sykmer** [comment]
and please add missing forks eg apple, maize, coffee.
Alternatively, you can write how to do it, I'll try to add them myself.
I already know what file to write what and where, but I don't know how to pack it back to .jar for the program to work properly.

Thank you .

**Comment by ForkFarmer** [comment]
Both issues fixed in 2.8.6 (jar on discord). Will push onto github eventually
