### ISSUE TITLE
silicoin - doesn't show the coins balance

### ISSUE THREAD

**Issue by klosmariusz007** [ForkFarmer/ForkFarmer#6]

**Comment by ForkFarmer** [comment]
right click -> debug -> wallet show. I'm guessing it will say "connection error". This means fork daemon is having problem with wallet remote procedure call.

**Comment by klosmariusz007** [comment]
Yes, it is exactly as you say. Is there any known workaround?

**Comment by ForkFarmer** [comment]
It's a problem with your setup, not ForkFarmer. Fix your port conflicts.
