### ISSUE TITLE
Request for Enhancement: Add blockchain progress to "Syncing" status

### ISSUE THREAD

**Issue by Lord-Malgus** [ForkFarmer/ForkFarmer#9]
I would like to see the syncing progress added to the Farm status when syncing is occurring.  This would allow the end user to 'see' the progress.

This can be taken from the chia.exe show -s output:

Example:
```
CMD_PROMPT> spare.exe show -s | findstr Blockchain
Current Blockchain Status: Syncing 679729/681475.
```

**Comment by ForkFarmer** [comment]
There are now 3 columns, Max Height "Max Peer Height"/ FN Height "Full Node" / W Height "Wallet Height". This should be sufficient to show synching progress.
